<a
          href="https://www.youtube.com/channel/UCF_Pcge4E7J8QnsOKl92jcQ"
          class="link"
        >
          <i class="bx bxl-youtube"></i>
        </a>
        <a
          href="https://www.linkedin.com/in/divyanshu-parate-882610254/"
          class="link"
        >
          <i class="bx bxl-linkedin-square"></i>
        </a>
        <a href="https://twitter.com/" class="link">
          <i class="bx bxl-twitter"></i>
        </a>
        <a href="https://www.instagram.com/div.zz_/" class="link">
          <i class="bx bxl-instagram"></i>
        </a>